version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  reviewers:
  - airhorns
  ignore:
  - dependency-name: omniauth
    versions:
    - 2.0.1
    - 2.0.2
    - 2.0.3
  - dependency-name: rails
    versions:
    - 6.1.2.1
    - 6.1.3
  - dependency-name: activerecord
    versions:
    - 6.1.2.1
    - 6.1.3
  - dependency-name: actionpack
    versions:
    - 6.1.2.1
    - 6.1.3
